# This file generated automatically by:
#   generate_sugar_files.py
# see wiki for more info:
#   https://github.com/ruslo/sugar/wiki/Collecting-sources

if(DEFINED ICU_SOURCE_COMMON_SUGAR_CMAKE_)
  return()
else()
  set(ICU_SOURCE_COMMON_SUGAR_CMAKE_ 1)
endif()

include(sugar_files)
include(sugar_include)

sugar_include(unicode)

sugar_files(
    ICU_UC_SOURCES
    propsvec.h
    unisetspan.h
    ucnv_bld.cpp
    cmemory.c
    unorm.cpp
    normalizer2impl.cpp
    locavailable.cpp
    propname.cpp
    unisetspan.cpp
    unistr_props.cpp
    sharedobject.h
    rbbicst.pl
    ubidi.c
    ucnv_imp.h
    util.h
    uniset_props.cpp
    uenumimp.h
    ucnvhz.c
    ubidiln.c
    uvectr32.h
    rbbiscan.cpp
    ubidiwrt.c
    udataswp.h
    uset_props.cpp
    ureslocs.h
    simplepatternformatter.h
    icuplug.cpp
    ubidi_props.c
    resbund_cnv.cpp
    ucln_cmn.cpp
    patternprops.h
    uprops.cpp
    uinit.cpp
    bytestrieiterator.cpp
    ustrtrns.cpp
    normalizer2impl.h
    ucnv2022.cpp
    loclikely.cpp
    ustr_cnv.h
    ucnv_io.cpp
    uchar.c
    ucmndata.c
    unifunct.cpp
    icudataver.c
    bytestriebuilder.cpp
    utrie2.cpp
    schriter.cpp
    sharedobject.cpp
    uresdata.c
    unifilt.cpp
    ucnv_ext.h
    uvector.cpp
    ucnvdisp.c
    stringpiece.cpp
    ucnvsel.cpp
    rbbisetb.h
    common.vcxproj
    uniset_closure.cpp
    listformatter.cpp
    ucnv_cnv.h
    ucnv_u16.c
    uresbund.cpp
    ustrenum.cpp
    localsvc.h
    uscript.c
    ucase_props_data.h
    filterednormalizer2.cpp
    stringtriebuilder.cpp
    rbbitblb.cpp
    ustrfmt.c
    ucnv_io.h
    dictionarydata.cpp
    putil.cpp
    propname_data.h
    udatamem.c
    brkiter.cpp
    rbbiscan.h
    unormimp.h
    locresdata.cpp
    utf_impl.c
    cstring.h
    umapfile.h
    ruleiter.cpp
    ucharstrie.cpp
    utrace.c
    ucase.h
    servrbf.cpp
    ustring.cpp
    ucol_data.h
    dictionarydata.h
    ulocimp.h
    patternprops.cpp
    sprpimpl.h
    locutil.cpp
    normlzr.cpp
    ucnvisci.c
    uhash_us.cpp
    uloc_tag.c
    uidna.cpp
    locdispnames.cpp
    messagepattern.cpp
    servnotf.cpp
    usc_impl.h
    uelement.h
    rbbirpt.txt
    ucnv_cnv.c
    caniter.cpp
    ucln.h
    unifiedcache.cpp
    ustr_cnv.cpp
    ucol_swp.cpp
    ucnv_u8.c
    ustrenum.h
    uchriter.cpp
    unistr_case_locale.cpp
    brkeng.cpp
    brkeng.h
    servnotf.h
    uts46.cpp
    serv.cpp
    uinvchar.c
    Makefile.in
    rbbirb.h
    ucnv_u7.c
    normalizer2.cpp
    uprops.h
    rbbidata.cpp
    uniset.cpp
    ucharstrieiterator.cpp
    utrie2.h
    rbbistbl.cpp
    uarrsort.c
    uresdata.h
    unistr.cpp
    punycode.h
    util.cpp
    ucat.c
    errorcode.cpp
    uvectr64.h
    serv.h
    uset.cpp
    common.rc
    ucnvbocu.cpp
    ucnvmbcs.cpp
    ucasemap.cpp
    parsepos.cpp
    uloc_keytype.cpp
    rbbinode.h
    cstring.c
    chariter.cpp
    umutex.cpp
    ucnvlat1.c
    ucharstriebuilder.cpp
    bytestrie.cpp
    utypeinfo.h
    utypes.c
    locid.cpp
    resbund.cpp
    mutex.h
    uiter.cpp
    ubrk.cpp
    uscript_props.cpp
    dtintrv.cpp
    ucnv_lmb.c
    ucnv_ct.c
    uchar_props_data.h
    usprep.cpp
    bmpset.cpp
    servls.cpp
    ustrcase.cpp
    servslkf.cpp
    udataswp.c
    uvectr64.cpp
    rbbidata.h
    charstr.h
    unames.cpp
    ucnv_err.c
    rbbi.cpp
    unormcmp.cpp
    unistr_cnv.cpp
    ucnvmbcs.h
    ucnv_u32.c
    wintz.c
    loadednormalizer2impl.cpp
    util_props.cpp
    unistr_titlecase_brkiter.cpp
    hash.h
    umath.c
    unistr_case.cpp
    norm2_nfc_data.h
    ulist.h
    ucln_imp.h
    uposixdefs.h
    messageimpl.h
    locutil.h
    uenum.c
    ustr_titlecase_brkiter.cpp
    propname.h
    common.vcxproj.filters
    charstr.cpp
    appendable.cpp
    ustack.cpp
    ustrcase_locale.cpp
    ustr_imp.h
    icuplugimp.h
    uhash.h
    usc_impl.c
    umapfile.c
    ucnvscsu.c
    utrie2_impl.h
    putilimp.h
    uvector.h
    rbbitblb.h
    locbased.cpp
    ucasemap_titlecase_brkiter.cpp
    punycode.cpp
    ucmndata.h
    dictbe.cpp
    utracimp.h
    uinvchar.h
    uvectr32.cpp
    rbbirpt.h
    usetiter.cpp
    ucnv.c
    propsvec.c
    servlk.cpp
    rbbirb.cpp
    ubidi_props_data.h
    cwchar.c
    ubidi_props.h
    bmpset.h
    utrie.h
    uhash.c
    msvcres.h
    uarrsort.h
    utrie.cpp
    uset_imp.h
    ulistformatter.cpp
    ucnv_cb.c
    ustrfmt.h
    locmap.h
    utrie2_builder.cpp
    cmemory.h
    uobject.cpp
    utext.cpp
    rbbisetb.cpp
    rbbinode.cpp
    uresimp.h
    wintz.h
    ucol_swp.h
    ubrkimpl.h
    unifiedcache.h
    servlkf.cpp
    umutex.h
    ucnv_bld.h
    ruleiter.h
    simplepatternformatter.cpp
    bytestream.cpp
    cpputils.h
    ucln_cmn.h
    uloc.cpp
    udatamem.h
    ucnv_ext.cpp
    udata.cpp
    ucase.cpp
    ustr_wcs.cpp
    norm2allmodes.h
    locbased.h
    ubidiimp.h
    ucnv_set.c
    cwchar.h
    ulist.c
    dictbe.h
    ures_cnv.c
    locmap.c
    ushape.cpp
    uassert.h
    servloc.h
)
