# This file generated automatically by:
#   generate_sugar_files.py
# see wiki for more info:
#   https://github.com/ruslo/sugar/wiki/Collecting-sources

if(DEFINED ICU_SOURCE_LAYOUT_SUGAR_CMAKE_)
  return()
else()
  set(ICU_SOURCE_LAYOUT_SUGAR_CMAKE_ 1)
endif()

include(sugar_files)

sugar_files(
    ICU_LAYOUT_SOURCES
    AttachmentPosnSubtables.h
    DefaultCharMapper.h
    StateTableProcessor.h
    MorphStateTables.h
    LEGlyphStorage.h
    GlyphPositionAdjustments.h
    SubstitutionLookups.h
    CanonData.cpp
    GlyphSubstitutionTables.cpp
    LigatureSubstitution.h
    StateTableProcessor2.cpp
    CanonShaping.cpp
    CharSubstitutionFilter.h
    IndicReordering.cpp
    SubtableProcessor2.cpp
    SegmentSingleProcessor2.h
    SegmentSingleProcessor.cpp
    ScriptAndLanguage.h
    Features.cpp
    LookupProcessor.h
    SimpleArrayProcessor2.h
    AlternateSubstSubtables.h
    KhmerReordering.h
    MorphTables2.cpp
    GDEFMarkFilter.cpp
    ContextualGlyphSubstProc.h
    MorphTables.h
    ContextualGlyphSubstitution.h
    SimpleArrayProcessor.cpp
    MarkToLigaturePosnSubtables.cpp
    GlyphPosnLookupProc.h
    ExtensionSubtables.h
    IndicRearrangementProcessor2.cpp
    GlyphSubstitutionTables.h
    GlyphDefinitionTables.h
    ExtensionSubtables.cpp
    CoverageTables.h
    HangulLayoutEngine.h
    GlyphLookupTables.cpp
    ArabicLayoutEngine.h
    KhmerLayoutEngine.h
    OpenTypeTables.h
    LEInsertionList.cpp
    SegmentSingleProcessor2.cpp
    MPreFixups.cpp
    OpenTypeUtilities.h
    LETypes.h
    AnchorTables.cpp
    SingleSubstitutionSubtables.cpp
    MarkToMarkPosnSubtables.cpp
    LEFontInstance.h
    GlyphSubstLookupProc.h
    CursiveAttachmentSubtables.cpp
    NonContextualGlyphSubstProc2.h
    MirroredCharData.cpp
    MultipleSubstSubtables.cpp
    SegmentArrayProcessor2.h
    ArabicLayoutEngine.cpp
    GlyphIterator.cpp
    LESwaps.h
    ScriptAndLanguageTags.cpp
    Lookups.cpp
    CanonShaping.h
    layout.rc
    KhmerLayoutEngine.cpp
    HangulLayoutEngine.cpp
    LEFontInstance.cpp
    LigatureSubstSubtables.cpp
    ThaiShaping.cpp
    ContextualGlyphSubstProc2.cpp
    IndicClassTables.cpp
    GlyphPosnLookupProc.cpp
    LEGlyphStorage.cpp
    TibetanLayoutEngine.cpp
    LEInsertionList.h
    LEScripts.h
    loengine.h
    ContextualSubstSubtables.h
    OpenTypeLayoutEngine.cpp
    LookupTables.h
    CursiveAttachmentSubtables.h
    TibetanLayoutEngine.h
    ArabicShaping.cpp
    GlyphPositioningTables.h
    KernTable.h
    HanLayoutEngine.h
    NonContextualGlyphSubstProc.h
    SingleTableProcessor.cpp
    IndicReordering.h
    PairPositioningSubtables.h
    StateTableProcessor.cpp
    OpenTypeLayoutEngine.h
    Makefile.in
    LETableReference.h
    MarkToBasePosnSubtables.cpp
    SingleTableProcessor2.cpp
    ScriptAndLanguage.cpp
    ClassDefinitionTables.h
    ContextualGlyphSubstProc2.h
    LigatureSubstProc.h
    ContextualGlyphInsertionProc2.cpp
    TrimmedArrayProcessor.cpp
    OpenTypeUtilities.cpp
    layout.vcxproj
    ThaiLayoutEngine.cpp
    IndicRearrangementProcessor2.h
    ClassDefinitionTables.cpp
    SimpleArrayProcessor2.cpp
    GXLayoutEngine2.h
    SingleTableProcessor.h
    LEGlyphFilter.h
    SegmentSingleProcessor.h
    MarkArrays.h
    CoverageTables.cpp
    ContextualGlyphInsertionProc2.h
    MPreFixups.h
    LigatureSubstProc2.h
    IndicRearrangementProcessor.cpp
    ThaiStateTables.cpp
    GlyphDefinitionTables.cpp
    LELanguages.h
    ContextualGlyphInsertion.h
    KhmerReordering.cpp
    TibetanReordering.h
    NonContextualGlyphSubstProc2.cpp
    ICUFeatures.h
    ThaiShaping.h
    LookupTables.cpp
    ArabicShaping.h
    SubtableProcessor.h
    IndicRearrangement.h
    ValueRecords.h
    MarkToLigaturePosnSubtables.h
    GlyphLookupTables.h
    LayoutEngine.cpp
    GXLayoutEngine.cpp
    LigatureSubstProc.cpp
    SubstitutionLookups.cpp
    AnchorTables.h
    KernTable.cpp
    loengine.cpp
    SinglePositioningSubtables.h
    SubtableProcessor2.h
    TibetanReordering.cpp
    Lookups.h
    LigatureSubstSubtables.h
    SimpleArrayProcessor.h
    NonContextualGlyphSubst.h
    IndicLayoutEngine.cpp
    StateTables.h
    MarkArrays.cpp
    TrimmedArrayProcessor.h
    GXLayoutEngine2.cpp
    MorphTables.cpp
    GlyphIterator.h
    TrimmedArrayProcessor2.h
    MultipleSubstSubtables.h
    DeviceTables.h
    DeviceTables.cpp
    GXLayoutEngine.h
    ShapingTypeData.cpp
    HanLayoutEngine.cpp
    PairPositioningSubtables.cpp
    SegmentArrayProcessor.cpp
    ContextualSubstSubtables.cpp
    SingleTableProcessor2.h
    ThaiLayoutEngine.h
    IndicRearrangementProcessor.h
    GlyphPositioningTables.cpp
    ValueRecords.cpp
    GlyphPositionAdjustments.cpp
    MarkToBasePosnSubtables.h
    GlyphSubstLookupProc.cpp
    ContextualGlyphSubstProc.cpp
    layout.vcxproj.filters
    IndicLayoutEngine.h
    SinglePositioningSubtables.cpp
    LigatureSubstProc2.cpp
    MarkToMarkPosnSubtables.h
    LayoutTables.h
    StateTableProcessor2.h
    ScriptAndLanguageTags.h
    LookupProcessor.cpp
    SingleSubstitutionSubtables.h
    SubtableProcessor.cpp
    GDEFMarkFilter.h
    SegmentArrayProcessor2.cpp
    TrimmedArrayProcessor2.cpp
    LayoutEngine.h
    NonContextualGlyphSubstProc.cpp
    AlternateSubstSubtables.cpp
    SegmentArrayProcessor.h
)
